site_name: Orchid Docs
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
  logo: assets/orchid-no-back.png
  favicon: assets/favicon.ico

extra_css:
  - styles/main.css
